### ISSUE TITLE
write_image assumes particular axisorder

### ISSUE THREAD

**Issue by k-dominik** [ome/ome-zarr-py#122]
Heyo, I just tried to naively write an ndarray to a an ome.zarr file, but didn't manage. My array was something like `numpy.zeros((100, 200, 1), dtype='uint8')` where I considered axes to be `yxc`.

of course when calling `write_image` I specified the `axes` argument. The `scaler`, however, will assume a certain axisorder. This leads to weird errors that are not super obvious.

I'd say this should be documented, or circumvented (e.g. making `Scaler` aware of axes, using a temporary adding the appropriate axes, etc...)

**Comment by will-moore** [comment]
Hi @k-dominik thanks for the feedback.
`write_image` should be doing a better job of validating the `axes` since the NGFF spec at https://ngff.openmicroscopy.org/latest/#image-layout says
`All image arrays must be up to 5-dimensional with dimension order (t, c, z, y, x)`.
The scaler currently only downsamples in `y and x` dimensions, so it will certainly give strange behaviour if either of those are 1.
